version: "3.9"
services:
  database:
    image: postgres:16.1
    ports:
      - "127.0.0.1:25432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env_local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  application:
    image: 'app_local:latest'
    depends_on:
      - database
    env_file:
      - .env_local
    build:
      context: ./backend
      dockerfile: ../docker/app.dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
    command: /start.sh

  webapp:
    image: 'webapp_local:latest'
    depends_on:
      - application
    env_file:
      - .env_local
    build:
      context: ./webapp
      dockerfile: ../docker/webapp.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./webapp:/webapp

volumes:
  db-data:
