version: "3.9"
services:
  database:
    image: postgres:16.1
    ports:
      - "127.0.0.1:25432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  application:
    image: 'app_local:latest'
    depends_on:
      - database
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    command: /start.sh

volumes:
  db-data:
